## Pre-commit setup

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: pretty-format-json
        args: [--indent=4, --autofix]
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        name: protect-branch
        alias: protect-branch
        args: [--branch=main, --branch=master]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations~=2.6.2
          - flake8-bandit~=2.1.2
          - flake8-bugbear~=21.4.3
          - flake8-docstrings~=1.6.0
          - flake8-isort~=4.0.0
          - flake8-string-format~=0.3.0
          - flake8-tidy-imports~=4.3.0
          - flake8-todo~=0.7
          - pep8-naming~=0.11

ci:
  skip: [no-commit-to-branch]
  autofix_prs: false
